### ISSUE TITLE
Cartodb json url is dead

### ISSUE THREAD

**Issue by QuestofIranon** [UMKC-Law/Parcel-Assessment-Tool#12]
```
GET  https://code4kc.cartodb.com/api/v2_1/viz/8167c2b8-0cf3-11e5-8080-0e9d821ea90d/viz.json [HTTP/1.1 404 Not Found 763ms]
```

The url for the json file that we usually get from cartodb to populate the map quit working sometime between yesterday and this evening.

@rlh-aagis 

It was:
https://code4kc.cartodb.com/api/v2_1/viz/8167c2b8-0cf3-11e5-8080-0e9d821ea90d/viz.json

**Comment by QuestofIranon** [comment]
disregard, I found how to retrieve the new one from cartodb. 

The new url is at: 
https://code4kc.cartodb.com/api/v2/viz/8167c2b8-0cf3-11e5-8080-0e9d821ea90d/viz.json
The only difference appears to be the change from v2_1 to v2.

You can see the change at d739cb89e34947a714e2eea66c8ae2007d2c18d5

**Comment by rlh-aagis** [comment]
@Questoflranon - Please bear with me, looking to merge updates today, Glad you got CartoDb export working, hopefully we will be able to expand use of CartoDb, no guarantees but hopeful, stay tuned!
