### ISSUE TITLE
Code for America Technology Award Submission

### ISSUE THREAD

**Issue by rlh-aagis** [UMKC-Law/Parcel-Assessment-Tool#16]
All, let's discuss and potentially work on this tomorrow (Monday) night for this project

http://awards.codeforamerica.org/

**Comment by rlh-aagis** [comment]
Submission deadline is July 13th

**Comment by QuestofIranon** [comment]
I'm not sure if we meet this criteria yet?

`Currently used by at least one U.S.-based government agency`

**Comment by zmon** [comment]
Deadline has passed.
