### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by Bcarlson92** [UMKC-Law/Parcel-Assessment-Tool#28]
Hi all,

I have a section of the presentation dedicated to project obstacles. One of the sections is data, and I was hoping one of the coders would go over some of the challenges revolving around the acquisition/storage/intergration/formating of data. 

If there is anything else we should touch on in the presentation please don't hesitate to let me know.

**Comment by rlh-aagis** [comment]
@Bcarlson92 I'd be happy to present on this topic.

**Comment by Bcarlson92** [comment]
Thanks Ron, Would you like me to put some bullet points up for you on the slide? If so what would you like them to be?

**Comment by rlh-aagis** [comment]
@Bcarlson92  Thanks Ben, here are the bullets. Is the data available? If so, what format? Where to store it?!

**Comment by Bcarlson92** [comment]
Great, its in the presentation.
