### ISSUE TITLE
Please email Paul

### ISSUE THREAD

**Issue by zmon** [UMKC-Law/Parcel-Assessment-Tool#3]
@Amertz08 and @rlh-aagis  could you email me at pbarham@codeforamerica.org.

**Comment by zmon** [comment]
If anyone on the team has any artifacts, mockups, pictures of the white board, notes on data please email them to me at pbarham@codeforamerica.org.

**Comment by rlh-aagis** [comment]
Hi Paul,

I hosted the PAT prototype on my website:
http://spatialconsortium.com/cfa/pat/index3.html . I know I need to
transfer the code to Git, I  will do so tomorrow.
Thanks Ron

**Comment by JRDeLisle** [comment]
Ron. The link pulls up a 404 error. Jim

Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by QuestofIranon** [comment]
The current Github is here: https://github.com/Amertz08/PAT
My fork is here: https://github.com/QuestofIranon/PAT
They should be equal right now though.

I plan to attend the meeting on monday

Joshua Herndon

**Comment by zmon** [comment]
@rlh-aagis @QuestofIranon I am assuming call code is in this gitub repo, or is there other code some place else?

**Comment by rlh-aagis** [comment]
Code is all located here

**Comment by QuestofIranon** [comment]
We aren't using the Python version now.
