### ISSUE TITLE
Hosting this off of Github

### ISSUE THREAD

**Issue by QuestofIranon** [UMKC-Law/Parcel-Assessment-Tool#34]
What options are available to us for hosting this off of Github if we were to build a backend using for example python?

**Comment by zmon** [comment]
Is there data that you will need besides what we are planning to provide or we could add in the address_api?
- https://github.com/codeforkansascity/address-api/wiki/Attributes-and-Data
- https://github.com/codeforkansascity/address-api/wiki/Wendell-Phillips-Data
- https://github.com/codeforkansascity/address-api/issues/16

**Comment by QuestofIranon** [comment]
As far as I know all of our data should be part of the address api already. The only other data would be the parcel geometries and geospatial data from cartodb, which should be fed from the api time to time anyway.

**Comment by JRDeLisle** [comment]
Paul. As to County Data, for the Building Envelope calculations we need the gross site size in square feet, and the lot dimensions (i.e., depth and width if regular). For displaying info, we need the assessed value of land and buildings, building size in SF, year built, other descriptive data, and ownership which we identified last Monday.
