### ISSUE TITLE
Creating image directory, adding logo

### ISSUE THREAD

**Issue by rlh-aagis** [UMKC-Law/Parcel-Assessment-Tool#5]
![legendbullets](https://cloud.githubusercontent.com/assets/3280502/8089078/3c7ce1b8-0f6b-11e5-9280-7f4e233db719.png)
![leftbkg](https://cloud.githubusercontent.com/assets/3280502/8089081/3e789052-0f6b-11e5-83cc-614254e44663.png)
![pattitle](https://cloud.githubusercontent.com/assets/3280502/8089089/42758f0c-0f6b-11e5-97e4-3622726ac181.png)
![overlay](https://cloud.githubusercontent.com/assets/3280502/8089094/4e133a76-0f6b-11e5-8c14-6171c0a7fdfa.png)
![title](https://cloud.githubusercontent.com/assets/3280502/8089105/63674be2-0f6b-11e5-890b-37c424733926.png)
![videobutton](https://cloud.githubusercontent.com/assets/3280502/8089106/658a9c62-0f6b-11e5-9e7d-70e35688b5d0.png)

**Comment by QuestofIranon** [comment]
This has actually been fixed, it should be marked as closed.
