### ISSUE TITLE
Suggestion on building an app

### ISSUE THREAD

**Issue by zmon** [UMKC-Law/Parcel-Assessment-Tool#8]
This is a good article on how someone developed an app.  There is no right way to build a application, so do not read this as the exact steps you will take, but read it as a general guide.  The article  http://mobile.smashingmagazine.com/2013/07/04/top-ten-app-part-1-idea-and-design?utm_source=buffer&utm_campaign=Buffer&utm_content=buffera3257&utm_medium=twitter

**Comment by QuestofIranon** [comment]
Oh, I meant to thank you for posting this, it was an interesting read.
